{% set name = "openff-evaluator" %}
{% set version = "0.4.2" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 136adc6a68b2edf1b17fe9ffb4b2de7e3f5a2a18c3073df099ebc330df1a6cce

build:
  number: 0
  
outputs:
  - name: {{ name|lower }}-base
    script: build_base.sh
    build:
      noarch: python

    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        - openff-toolkit-base =>0.11.0
        - pandas
        - openmm >=7.6
        - networkx
        - packmol
        - pymbar
        # https://github.com/openforcefield/openff-evaluator/issues/470#issuecomment-1248878110
        - mdtraj !=1.9.5
        - dask >=2.7.0
        - distributed >=2.7.0
        - dask-jobqueue >=0.8.0
        - uncertainties
        - openmmtools
        - pyyaml
        - requests
        - rdkit
        - python-dateutil
        - pydantic <2.0.0a0


    test:
      imports:
        - openff.evaluator

  - name: {{ name|lower }}
    build:
      noarch: python

    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        - yank >=0.25.2
        - mdtraj >=1.9.3,<=1.9.4
        - {{ pin_subpackage('openff-evaluator-base', exact=True) }}

    test:
      imports:
        - openff.evaluator

about:
  home: https://github.com/openforcefield/openff-evaluator
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A physical property evaluation toolkit from the Open Forcefield Consortium.
  description: |
    A physical property evaluation toolkit from the Open Forcefield Consortium.
  doc_url: https://github.com/openforcefield/openff-evaluator
  dev_url: https://github.com/openforcefield/openff-evaluator

extra:
  recipe-maintainers:
    - simonboothroyd
    - mattwthompson
    - j-wags
