{% set name = "openff-evaluator" %}
{% set version = "0.3.8" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2797856f7f999ff02d550f721b9f3598d0da71b6bfdcde2d2e01d42f2ae72f5d

build:
  number: 0
  
outputs:
  - name: {{ name|lower }}-base
    script: build_base.sh
    build:
      noarch: python

    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - openff-toolkit-base >=0.10.0
        - numpy
        - pandas
        - openmm >=7.6.0
        - networkx
        - pint
        - packmol
        - pymbar >=3.0.5
        - mdtraj >=1.9.3
        - dask >=2.7.0
        - distributed >=2.7.0
        - dask-jobqueue >=0.7.0
        - uncertainties
        - openmmtools
        - pyyaml
        - requests
        - rdkit
        - cmiles
        - python-dateutil
        - pydantic

  - name: {{ name|lower }}
    build:
      noarch: python

    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - yank >=0.25.2
        - {{ pin_subpackage('openff-evaluator-base', exact=True) }}

    test:
      imports:
        - openff.evaluator

about:
  home: https://github.com/openforcefield/openff-evaluator
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A physical property evaluation toolkit from the Open Forcefield Consortium.
  description: |
    A physical property evaluation toolkit from the Open Forcefield Consortium.
  doc_url: https://github.com/openforcefield/openff-evaluator
  dev_url: https://github.com/openforcefield/openff-evaluator

extra:
  recipe-maintainers:
    - simonboothroyd
